version: "3"
services:
  webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: always
    environment:
      - LOAD_EX=y
    volumes:
      - ~/airflow/dags:/opt/airflow/dags
      - ~/airflow/logs:/opt/airflow/logs
      - ~/airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow webserver"
