[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest="0.11"
tokio={version = "1",features = ["full"]}
aws-config = "0.55.1"
aws-sdk-sts = "0.26.0"
#actix-web="4"