apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myserviceaccount-read-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1

kind: ServiceAccount
metadata:
  name: sample-serviceaccount
  namespace: default
imagePullSecrets:
  - name: myregistrkey

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myserviceaccount-read-pods
subjects:
  - kind: ServiceAccount
    name: sample-serviceaccount
    namespace: default
roleRef:
  kind: Role
  name: myserviceaccount-read-pods
  apiGroup: rbac.authorization.k8s.io
